# Generated by Django 4.2.7 on 2023-12-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_recipe_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serve',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='recipe',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
